import { Link } from '@tanstack/react-router';
import { ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLang } from '@/lib/lang';
import { branches, waLink, regionOf, type Branch, PageHeading, ServiceGrid, SiteLayout } from './vow-site';

export function BranchPage({ branch }: { branch: Branch }) {
  const { lang, t } = useLang();
  const n = branch.name;
  const idx = branches.indexOf(branch);
  const gallery = [branch.image, branches[(idx + 1) % branches.length]?.image ?? branch.image, branches[(idx + 2) % branches.length]?.image ?? branch.image];
  return <SiteLayout>
    <PageHeading eyebrow={t(`Beranda / Cabang / ${n}`, `Home / Branches / ${n}`)} title={`Virtual Office ${n}`} description={t(`Alamat bisnis dan layanan pendukung di ${n}. Temukan pilihan yang sesuai dengan kebutuhan usaha Anda.`, `Business address and support services in ${n}. Find the option that fits your business needs.`)} />
    <section className="section"><div className="wrap branch-intro"><div className="branch-feature-photo"><img src={branch.image} alt={t(`Ilustrasi ruang kerja di ${n}`, `Workspace illustration in ${n}`)} width="1280" height="800" /><span className="image-tag">{t('Ilustrasi ruang kerja, bukan foto kantor VOW', 'Workspace illustration, not a photo of a VOW office')}</span></div><div className="branch-info"><p className="eyebrow">{t('Cabang VOW', 'VOW branch')}</p><h2>{t('Informasi kantor', 'Office information')}</h2><dl><dt>{t('Lokasi', 'Location')}</dt><dd>{regionOf(branch, lang)}</dd><dt>{t('Alamat lengkap', 'Full address')}</dt><dd>{t('Hubungi tim VOW untuk informasi alamat resmi.', 'Contact the VOW team for the official address.')}</dd><dt>WhatsApp</dt><dd><a className="branch-wa" href={waLink(branch, lang)} target="_blank" rel="noopener noreferrer">{branch.wa}</a></dd><dt>{t('Jam operasional', 'Opening hours')}</dt><dd>{t('Informasi resmi segera tersedia.', 'Official information coming soon.')}</dd></dl><div className="branch-ctas"><Button asChild><a href={waLink(branch, lang)} target="_blank" rel="noopener noreferrer">{t(`Chat WhatsApp ${n}`, `WhatsApp chat ${n}`)} <ArrowRight size={16}/></a></Button><Button asChild variant="outline"><Link to="/kontak">{t('Kirim pertanyaan', 'Send an enquiry')} <ArrowRight size={16}/></Link></Button></div></div></div></section>
    <section className="section section-alt"><div className="wrap"><div className="section-heading"><p className="eyebrow">{t('Area cabang', 'Branch area')}</p><h2>{t(`Lokasi ${n}`, `${n} location`)}</h2><p>{t(`Peta berikut menunjukkan area ${n}, bukan lokasi kantor spesifik.`, `The map below shows the ${n} area, not a specific office location.`)}</p></div><iframe className="area-map" title={t(`Peta area ${n}`, `${n} area map`)} loading="lazy" src={`https://www.google.com/maps?q=${encodeURIComponent(n + ', Indonesia')}&output=embed`} referrerPolicy="no-referrer-when-downgrade" /></div></section>
    <section className="section"><div className="wrap"><div className="section-heading"><p className="eyebrow">{t('Galeri', 'Gallery')}</p><h2>{t('Gambaran ruang kerja', 'Workspace overview')}</h2><p>{t('Visual ilustrasi untuk memberi gambaran suasana kerja. Foto kantor asli akan ditambahkan setelah tersedia.', 'Illustrative visuals to show the working atmosphere. Real office photos will be added once available.')}</p></div><div className="gallery-grid">{gallery.map((img, i) => <div key={i}><img src={img} alt={t(`Ilustrasi suasana ruang kerja ${i + 1}`, `Workspace atmosphere illustration ${i + 1}`)} loading="lazy" width="1280" height="800" /></div>)}</div></div></section>
    <section className="section section-alt"><div className="wrap"><div className="section-heading"><p className="eyebrow">{t('Yang kami tawarkan', 'What we offer')}</p><h2>{t(`Layanan di ${n}`, `Services in ${n}`)}</h2></div><ServiceGrid /><h3 className="more-title">{t('Cabang lainnya', 'Other branches')}</h3><div className="branch-links">{branches.filter(b => b.slug !== branch.slug).map(b => <Button key={b.slug} asChild variant="outline"><Link to={`/${b.slug}`}>{b.name} <ArrowRight size={16}/></Link></Button>)}</div></div></section>
  </SiteLayout>;
}
