import { Link } from '@tanstack/react-router';
import { ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { branches, type Branch, PageHeading, ServiceGrid, SiteLayout } from './vow-site';

export function BranchPage({ branch }: { branch: Branch }) {
  return <SiteLayout>
    <PageHeading eyebrow={`Beranda / Cabang / ${branch.name}`} title={`Virtual Office ${branch.name}`} description={`Alamat bisnis dan layanan pendukung di ${branch.name}. Temukan pilihan yang sesuai dengan kebutuhan usaha Anda.`} />
    <section className="section"><div className="wrap branch-intro"><div className="branch-feature-photo"><img src={branch.image} alt={`Ilustrasi ruang kerja di ${branch.name}`} width="1280" height="800" /><span className="image-tag">Ilustrasi ruang kerja, bukan foto kantor VOW</span></div><div className="branch-info"><p className="eyebrow">Cabang VOW</p><h2>Informasi kantor</h2><dl><dt>Lokasi</dt><dd>{branch.region}</dd><dt>Alamat lengkap</dt><dd>Hubungi tim VOW untuk informasi alamat resmi.</dd><dt>WhatsApp & jam operasional</dt><dd>Informasi resmi segera tersedia.</dd></dl><Button asChild><a href="#kontak">Lihat informasi kontak <ArrowRight size={16}/></a></Button></div></div></section>
    <section className="section section-alt"><div className="wrap"><div className="section-heading"><p className="eyebrow">Area cabang</p><h2>Lokasi {branch.name}</h2><p>Peta berikut menunjukkan area {branch.name}, bukan lokasi kantor spesifik.</p></div><iframe className="area-map" title={`Peta area ${branch.name}`} loading="lazy" src={`https://www.google.com/maps?q=${encodeURIComponent(branch.name + ', Indonesia')}&output=embed`} referrerPolicy="no-referrer-when-downgrade" /></div></section>
    <section className="section"><div className="wrap"><div className="section-heading"><p className="eyebrow">Galeri</p><h2>Gambaran ruang kerja</h2><p>Visual ilustrasi untuk memberi gambaran suasana kerja. Foto kantor asli akan ditambahkan setelah tersedia.</p></div><div className="gallery-grid">{[branch.image, branches[(branches.indexOf(branch) + 1) % branches.length]?.image ?? branch.image, branches[(branches.indexOf(branch) + 2) % branches.length]?.image ?? branch.image].map((img, i) => <div key={i}><img src={img} alt={`Ilustrasi suasana ruang kerja ${i + 1}`} loading="lazy" width="1280" height="800" /></div>)}</div></div></section>
    <section className="section section-alt"><div className="wrap"><div className="section-heading"><p className="eyebrow">Yang kami tawarkan</p><h2>Layanan di {branch.name}</h2></div><ServiceGrid /><h3 className="more-title">Cabang lainnya</h3><div className="branch-links">{branches.filter(b => b.slug !== branch.slug).map(b => <Button key={b.slug} asChild variant="outline"><Link to={`/${b.slug}`}>{b.name} <ArrowRight size={16}/></Link></Button>)}</div></div></section>
  </SiteLayout>;
}
